# This is a basic workflow to help you get started with Actions

name: SSL EXPIRY

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  chk_ssl_expiry:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout repo
        # Checkout the repository code
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run the script
        run: |
          chmod +x .github/scripts/test.sh
          ./.github/scripts/test.sh ${{ secrets.SSL_WEBHOOK }}
